minimum_pre_commit_version: '3.0.0'

repos:
  - repo: local
    hooks:
      - id: import-hacking-fixer
        name: import-hacking-fixer
        entry: ihf fix
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
